### PR TITLE
Access params and controller

### PR DESCRIPTION
**Pull request by shlub**
I regularly need to monkey patch the `FakeViewContext' to be able to access params and the current controller.

What do you think?

### CODE REVIEW

**Comment by splattael** [comment]
Ok in general but I wonder where do you need to access `controller` via `view_context`.
Do you have an example for this?

**Comment by shlub** [comment]
Generating a css class based on the controller/action for example.

**Comment by jnbt** [comment]
LGTM

**Comment by splattael** [comment]
:shipit:

**Comment by jnbt** [comment]
Just a fun fact: I tried to get a feeling of the real ViewContext's "interface":

```
view_context.public_methods.count # => 794 (in production), 866 (in development)
```

**Pull request merged**
